[package]
name = "auth-api"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4"
bcrypt = "0.16.0"
rand = "0.8.5"
serde = "1.0.216"
serde_json = "1.0.134"
sha2 = "0.10.8"
sqlx = { version = "0.8", features = [ "runtime-tokio", "postgres" ] }
